export interface Transportloss {
  Claim_Discrepancy: number, //0.0,
  Company: string, //TBBM PADALARANG,
  Compartment: string, //1,
  Date: string, //2020-10-06,
  Delivery_Discrepancy: number, //0.0,
  Density_Obs: number, //765.0,
  Driver: string, //Ece Sugandi,
  Driver_Assistant: string, //Sugia Purnawan,
  Height_After: number, //0.0,
  Height_Before: number, //1345.0,
  LO: string, //8057819861,
  No: string, //1,
  Product: string, //PERTALITE,
  SPBU: string, //3443309,
  Sensitivity: number, //3.508,
  State: string, //confirm,
  Temperatur_Obs: number, //30.0,
  Tolerance: number, //0.0,
  Tolerance_Discrepancy: number, //0.0,
  Ttl_Loss: number, //4020.0,
  Ttl_Loss_Claim: number, //4020.0,
  Vehicle: string, //B9274SFU,
  Vol_After: number, //3980.0,
  Vol_Before: number, //8000.0
}